CREATE TABLE refresh_token
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    created_by  BIGINT,
    updated_by  BIGINT,
    user_id     BIGINT,
    token       VARCHAR(255),
    expiry_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_refreshtoken PRIMARY KEY (id)
);

CREATE TABLE user_roles
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role_type VARCHAR(255),
    CONSTRAINT pk_user_roles PRIMARY KEY (id)
);
insert into user_roles (id, role_type)
values (1, 'ROLE_ADMIN');
insert into user_roles (id, role_type)
values (1, 'ROLE_USER');

CREATE TABLE user_table
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    created_by        BIGINT,
    updated_by        BIGINT,
    email             VARCHAR(255),
    password          VARCHAR(255),
    is_google_account BOOLEAN,
    CONSTRAINT pk_user_table PRIMARY KEY (id)
);

CREATE TABLE user_user_roles
(
    user_id      BIGINT NOT NULL,
    user_role_id BIGINT NOT NULL,
    CONSTRAINT pk_user_user_roles PRIMARY KEY (user_id, user_role_id)
);

ALTER TABLE refresh_token
    ADD CONSTRAINT FK_REFRESHTOKEN_ON_USER FOREIGN KEY (user_id) REFERENCES user_table (id);

ALTER TABLE user_user_roles
    ADD CONSTRAINT fk_useuserol_on_user FOREIGN KEY (user_id) REFERENCES user_table (id);

ALTER TABLE user_user_roles
    ADD CONSTRAINT fk_useuserol_on_user_role FOREIGN KEY (user_role_id) REFERENCES user_roles (id);