CREATE TABLE measure
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    created_by BIGINT,
    updated_by BIGINT,
    name       VARCHAR(255),
    CONSTRAINT pk_measure PRIMARY KEY (id)
);
CREATE TABLE food
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    created_by BIGINT,
    updated_by BIGINT,
    name       VARCHAR(255),
    CONSTRAINT pk_food PRIMARY KEY (id)
);
CREATE TABLE conversion_factor
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    created_by BIGINT,
    updated_by BIGINT,
    food_id    BIGINT,
    measure_id BIGINT,
    factor     FLOAT,
    CONSTRAINT pk_conversion_factor PRIMARY KEY (id)
);

ALTER TABLE conversion_factor
    ADD CONSTRAINT FK_CONVERSION_FACTOR_ON_FOOD FOREIGN KEY (food_id) REFERENCES food (id);

ALTER TABLE conversion_factor
    ADD CONSTRAINT FK_CONVERSION_FACTOR_ON_MEASURE FOREIGN KEY (measure_id) REFERENCES measure (id);


CREATE TABLE nutrient
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    created_by BIGINT,
    updated_by BIGINT,
    name       VARCHAR(255),
    CONSTRAINT pk_nutrient PRIMARY KEY (id)
);