CREATE TABLE recipe
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    created_by BIGINT,
    updated_by BIGINT,
    name       VARCHAR(255),
    CONSTRAINT pk_recipe PRIMARY KEY (id)
);

CREATE TABLE recipe_food_
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at           TIMESTAMP WITHOUT TIME ZONE,
    updated_at           TIMESTAMP WITHOUT TIME ZONE,
    created_by           BIGINT,
    updated_by           BIGINT,
    food_id              BIGINT,
    conversion_factor_id BIGINT,
    quantity             FLOAT,
    recipe_id            BIGINT,
    CONSTRAINT pk_recipe_food_ PRIMARY KEY (id)
);

CREATE TABLE recipe_recipe_foods
(
    recipe_id       BIGINT NOT NULL,
    recipe_foods_id BIGINT NOT NULL,
    CONSTRAINT pk_recipe_recipefoods PRIMARY KEY (recipe_id, recipe_foods_id)
);

ALTER TABLE recipe_recipe_foods
    ADD CONSTRAINT uc_recipe_recipe_foods_recipefoods UNIQUE (recipe_foods_id);

ALTER TABLE recipe_food_
    ADD CONSTRAINT FK_RECIPE_FOOD__ON_RECIPE FOREIGN KEY (recipe_id) REFERENCES recipe (id);

ALTER TABLE recipe_recipe_foods
    ADD CONSTRAINT fk_recrecfoo_on_recipe FOREIGN KEY (recipe_id) REFERENCES recipe (id);

ALTER TABLE recipe_recipe_foods
    ADD CONSTRAINT fk_recrecfoo_on_recipe_food FOREIGN KEY (recipe_foods_id) REFERENCES recipe_food_ (id);