CREATE TABLE refresh_token
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    created_by  BIGINT,
    updated_by  BIGINT,
    user_id     BIGINT,
    token       VARCHAR(255),
    expiry_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_refreshtoken PRIMARY KEY (id)
);