version: '3'
services:
  postgres_recipe_manager:
    image: postgres
    volumes:
      - postgres-data-recipe-manager:/var/lib/postgresql/data
    ports:
      - "${RECIPE_MANAGER_SERVICE_DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_DB: ${RECIPE_MANAGER_DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  postgres_food_nutrients:
    image: postgres
    volumes:
      - postgres-data-foot-nutrients:/var/lib/postgresql/data
    ports:
      - "${FOOD_NUTRIENTS_SERVICE_DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_DB: ${FOOD_NUTRIENTS_DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  postgres_user:
    image: postgres
    volumes:
      - postgres-data-user:/var/lib/postgresql/data
    ports:
      - "${USER_SERVICE_DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_DB: ${USER_SERVICE_DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
volumes:
  postgres-data-recipe-manager:
  postgres-data-foot-nutrients:
  postgres-data-user: