CREATE TABLE food
(
    id          BIGINT NOT NULL,
    name        VARCHAR(255),
    name_french VARCHAR(255),
    CONSTRAINT pk_food PRIMARY KEY (id)
);
CREATE TABLE measure
(
    id          BIGINT NOT NULL,
    name        VARCHAR(255),
    name_french VARCHAR(255),
    CONSTRAINT pk_measure PRIMARY KEY (id)
);
CREATE TABLE conversion_factor
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    food_id    BIGINT                                  NOT NULL,
    measure_id BIGINT                                  NOT NULL,
    factor     FLOAT,
    CONSTRAINT pk_conversion_factor PRIMARY KEY (id)
);

ALTER TABLE conversion_factor
    ADD CONSTRAINT FK_CONVERSION_FACTOR_ON_FOOD FOREIGN KEY (food_id) REFERENCES food (id) ON DELETE CASCADE;

ALTER TABLE conversion_factor
    ADD CONSTRAINT FK_CONVERSION_FACTOR_ON_MEASURE FOREIGN KEY (measure_id) REFERENCES measure (id) ON DELETE CASCADE;