CREATE TABLE recipe
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    created_by BIGINT,
    updated_by BIGINT,
    name       VARCHAR(255),
    CONSTRAINT pk_recipe PRIMARY KEY (id)
);
CREATE TABLE recipe_food
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at           TIMESTAMP WITHOUT TIME ZONE,
    updated_at           TIMESTAMP WITHOUT TIME ZONE,
    created_by           BIGINT,
    updated_by           BIGINT,
    food_id              BIGINT NOT NULL,
    conversion_factor_id BIGINT NOT NULL,
    quantity             FLOAT,
    recipe_id            BIGINT                                  NOT NULL,
    CONSTRAINT pk_recipe_food PRIMARY KEY (id)
);

ALTER TABLE recipe_food
    ADD CONSTRAINT FK_RECIPE_FOOD_ON_RECIPE FOREIGN KEY (recipe_id) REFERENCES recipe (id) ON DELETE SET NULL;
